### ISSUE TITLE
Update operations can cause invalid iterator return

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/offheap-store#17]
If a update to a mapping occurs when an iterator is still live against a old table version (aged out due to resize) then the update is incorrectly propagated to the table (the mapping is removed rather than being updated to the new encoding).

**Comment by ljacomet** [comment]
I believe this bug is applicable to the 2.0.0 version as well. Should we open a 2.0 branch for a future 2.0.1 release?

**Comment by chrisdennis** [comment]
I guess the owner of one of the downstream projects would have to decide that they wanted the fix, and then request it, at which point we could think about helping them. ;)
