### ISSUE TITLE
MappedPageSource doesn't handle interaction of interrupted threads with it's FileChannel

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/offheap-store#49]
MappedPageSource uses a `FileChannel` internally to truncate and extend the underlying file, map regions, and flush changes out.  These accesses need to be made safe when the calling thread is being interrupted.  This can/should probably be done in the same way that we do for `FileBackedStorageEngine`.

**Comment by nikowitt** [comment]
Hi, are there any news regarding this? We experience the same/similar assue after moving to EhCache 3.5 and having the ability to interrupt threads.

**Comment by cdalexndr** [comment]
Original issue: https://groups.google.com/forum/#!topic/ehcache-users/QpelMYURf4k
